const doctors = [
  { name: "Dr. Sarah Johnson", title: "Senior Consultant Cardiologist", credentials: ["MBBS", "FCPS", "Cardiology"], specialization: "Heart & Cardiovascular Specialist", specializationDesc: "Dedicated to diagnosing and treating complex heart conditions with modern cardiovascular care.", tags: ["Heart Disease", "Hypertension", "ECG", "Chest Pain", "Heart Failure"], patients: "850+", rating: "4.9★", experience: "12+", timing: "Mon-Sat • 9AM-6PM", trustLine: "Trusted by 850+ patients for exceptional cardiac care.", image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=1200" },
  { name: "Dr. Michael Chen", title: "Orthopedic & Joint Specialist", credentials: ["MBBS", "MS Orthopedics", "Sports Med"], specialization: "Orthopedic Surgery & Sports Injury", specializationDesc: "Expert in joint replacement, arthroscopy, and sports trauma rehabilitation for active lifestyles.", tags: ["Knee Pain", "Fracture", "Arthritis", "Sports Injury", "Joint Pain"], patients: "1.2k+", rating: "4.8★", experience: "15+", timing: "Mon-Fri • 8AM-2PM", trustLine: "Over 1,200 patients restored mobility with advanced orthopedic care.", image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1200" },
  { name: "Dr. Priya Sharma", title: "Pediatric Care Specialist", credentials: ["MD", "DNB Pediatrics", "Child Health"], specialization: "Child Wellness & Vaccination Expert", specializationDesc: "Compassionate pediatric care from infancy to adolescence, immunizations and developmental milestones.", tags: ["Child Fever", "Vaccination", "Growth", "Asthma", "Nutrition"], patients: "2.1k+", rating: "4.9★", experience: "9+", timing: "Tue-Sat • 10AM-4PM", trustLine: "Cherished by 2000+ families for gentle, evidence-based pediatric care.", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=1200" },
  
  // Updated Images below:
  { name: "Dr. James O'Connor", title: "Neurology & Stroke Specialist", credentials: ["MD", "DM Neurology", "Stroke Care"], specialization: "Brain & Nervous System Specialist", specializationDesc: "Advanced management of migraines, epilepsy, stroke rehabilitation and neurodegenerative disorders.", tags: ["Migraine", "Epilepsy", "Stroke", "Memory Loss", "Neuropathy"], patients: "980+", rating: "4.7★", experience: "18+", timing: "Mon, Wed, Fri • 11AM-5PM", trustLine: "Internationally trained neurologist with focus on minimally invasive treatments.", image: "" },
  { name: "Dr. Emily Rodriguez", title: "Pulmonary Medicine Director", credentials: ["MD", "Pulmonology", "Critical Care"], specialization: "Lung & Respiratory Health", specializationDesc: "Asthma, COPD, sleep apnea and interventional pulmonology for chronic respiratory wellness.", tags: ["Asthma", "COPD", "Bronchitis", "Sleep Apnea", "Lung Fibrosis"], patients: "1.5k+", rating: "4.8★", experience: "11+", timing: "Mon-Thu • 1PM-7PM", trustLine: "Helped 1500+ patients breathe easier with personalized pulmonary plans.", image: "https://images.unsplash.com/photo-1579684385127-1ecd15d5bfbcc?w=1200" },
  { name: "Dr. William Hayes", title: "Urology & Kidney Specialist", credentials: ["MS", "MCh Urology", "Renal Medicine"], specialization: "Advanced Urological Surgery", specializationDesc: "Minimally invasive procedures for kidney stones, prostate conditions and male reproductive health.", tags: ["Kidney Stone", "UTI", "Prostate", "Incontinence", "Male Health"], patients: "2.3k+", rating: "4.9★", experience: "20+", timing: "Wed-Sun • 9AM-3PM", trustLine: "Pioneer in laser kidney stone treatment with 98% success satisfaction.", image: "https://images.unsplash.com/photo-1651008376811-b904bc6fa977?w=1200" },
  { name: "Dr. Aisha Khan", title: "Dermatology & Aesthetics", credentials: ["MD", "Dermatology", "Cosmetology"], specialization: "Skin, Hair & Laser Specialist", specializationDesc: "Evidence-based dermatology for acne, psoriasis, anti-aging and hair restoration.", tags: ["Acne", "Eczema", "Psoriasis", "Hair Fall", "Skin Allergy"], patients: "1.8k+", rating: "4.9★", experience: "8+", timing: "Mon-Sat • 12PM-6PM", trustLine: "Recognized for flawless results in complex dermatological cases.", image: "https://images.unsplash.com/photo-1551601651-2a8555e8a5b2?w=1200" },
  { name: "Dr. David Kim", title: "ENT & Head-Neck Surgeon", credentials: ["MBBS", "FRCS ENT", "Otology"], specialization: "Ear, Nose & Throat Excellence", specializationDesc: "Comprehensive care for sinusitis, hearing restoration, vertigo and voice disorders.", tags: ["Sinusitis", "Hearing Loss", "Tonsillitis", "Vertigo", "Snoring"], patients: "1.1k+", rating: "4.7★", experience: "14+", timing: "Tue, Thu, Sat • 10AM-4PM", trustLine: "Advanced endoscopic sinus surgery with rapid recovery protocols.", image: "https://static.vecteezy.com/system/resources/thumbnails/026/375/249/small/ai-generative-portrait-of-confident-male-doctor-in-white-coat-and-stethoscope-standing-with-arms-crossed-and-looking-at-camera-photo.jpg" },
  
  { name: "Dr. Grace Muthoni", title: "Psychiatry & Mental Wellness", credentials: ["MD", "Psychiatry", "Behavioral Therapy"], specialization: "Mind & Emotional Health", specializationDesc: "Holistic psychiatric care for anxiety, depression, stress management and therapy.", tags: ["Anxiety", "Depression", "Stress", "Insomnia", "Therapy"], patients: "950+", rating: "4.8★", experience: "10+", timing: "Mon-Fri • 2PM-8PM", trustLine: "Patient-centered therapy & medication management for lasting wellbeing.", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDQdtoUxw0HFLkef9F_TVCE5lyo1ilgZchrTMWWF452kuoqLwsnd3PdSk&s=10" },
  { name: "Dr. Rajiv Mehta", title: "Gastroenterology & Liver", credentials: ["DM", "Gastroenterology", "Hepatology"], specialization: "Digestive & Liver Health", specializationDesc: "Specialized in IBS, ulcer management, endoscopy and advanced liver disease treatment.", tags: ["Acidity", "IBS", "Ulcer", "Liver Disease", "Constipation"], patients: "1.4k+", rating: "4.8★", experience: "16+", timing: "Mon-Sat • 8AM-1PM", trustLine: "Renowned gastroenterologist with high patient satisfaction scores.", image: "https://thumbs.dreamstime.com/b/indian-doctor-mature-male-medical-standing-inside-hospital-handsome-model-portrait-46325210.jpg" },
  { name: "Dr. Olivia Bennett", title: "Ophthalmology & LASIK", credentials: ["MS", "Ophthalmology", "Refractive Surgery"], specialization: "Vision & Eye Care Specialist", specializationDesc: "Cataract surgery, glaucoma management, LASIK and advanced retinal diagnostics.", tags: ["Cataract", "Glaucoma", "Dry Eye", "LASIK", "Vision Care"], patients: "1.7k+", rating: "4.9★", experience: "13+", timing: "Tue-Sun • 9:30AM-3:30PM", trustLine: "Performed 3000+ successful refractive surgeries with precision.", image: "https://thumbs.dreamstime.com/b/african-american-man-male-doctor-27757329.jpg" },
  { name: "Dr. Carlos Mendez", title: "Endocrinology & Diabetes", credentials: ["MD", "Endocrinology", "Metabolism"], specialization: "Hormone & Diabetes Care", specializationDesc: "Expert in type 1 & 2 diabetes, thyroid disorders, obesity management and metabolic health.", tags: ["Diabetes", "Thyroid", "Hormones", "Obesity", "Metabolism"], patients: "2.0k+", rating: "4.8★", experience: "17+", timing: "Mon-Thu • 10AM-5PM", trustLine: "Internationally published endocrinologist transforming diabetic care.", image: "https://img.magnific.com/premium-photo/unaltered-portrait-happy-caucasian-male-doctor-with-arms-crossed-smiling-hospital-corridor-friendly-job-satisfaction-hospital-medical-healthcare-services_13339-340803.jpg?semt=ais_hybrid&w=740&q=80" }
];

const emergencyDoctors = [
  { name: "Dr. Michael Smith", title: "Emergency & Critical Care Specialist", coverage: "24/7 Trauma Response Unit", coverageDesc: "Immediate medical assistance for trauma, critical care, accidents, ICU support and life-threatening emergencies.", tags: ["Trauma Care", "ICU Support", "Accidents", "Emergency Surgery", "Critical Care"], response: "5 Min", available: "24/7", cases: "5000+", hotline: "+1 (800) 911-CARE", image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1200" },
  { name: "Dr. Sarah Williams", title: "Cardiac Emergency Specialist", coverage: "Cardiac Crisis Unit", coverageDesc: "Specialized in heart attacks, cardiac arrest, arrhythmias, and acute coronary syndrome. Immediate cath lab activation.", tags: ["Heart Attack", "Cardiac Arrest", "ECG", "Defibrillation", "Acute MI"], response: "4 Min", available: "24/7", cases: "4200+", hotline: "+1 (800) HEART-911", image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=1200" },
  { name: "Dr. James Rodriguez", title: "Stroke & Neuro Critical Care", coverage: "Stroke & Neuro Critical Care", coverageDesc: "Rapid response for ischemic stroke, hemorrhagic stroke, seizures, and traumatic brain injury. Golden hour specialist.", tags: ["Stroke", "Brain Injury", "Seizures", "Neuro ICU", "Thrombectomy"], response: "6 Min", available: "24/7", cases: "2800+", hotline: "+1 (800) STROKE-NOW", image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=1200" },
  { name: "Dr. Emily Foster", title: "Pediatric Emergency Medicine", coverage: "Pediatric Critical Care", coverageDesc: "Specialized emergency care for infants and children. Pediatric resuscitation, febrile seizures, and acute pediatric trauma.", tags: ["Pediatric Resuscitation", "Febrile Seizures", "Child Trauma", "NICU", "Emergency"], response: "5 Min", available: "24/7", cases: "5100+", hotline: "+1 (800) KID-EMERG", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=1200" },
  { name: "Dr. Robert Okonkwo", title: "Respiratory Emergency Specialist", coverage: "Pulmonary Crisis Unit", coverageDesc: "Expert in respiratory failure, severe asthma, COPD exacerbation, pulmonary embolism, and critical care ventilation.", tags: ["Respiratory Failure", "Asthma Crisis", "COPD", "Pulmonary Embolism", "Ventilator"], response: "5 Min", available: "24/7", cases: "3900+", hotline: "+1 (800) LUNG-911", image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=1200" },
  { name: "Dr. Anita Sharma", title: "Toxicology & Poison Control", coverage: "Medical Toxicology Unit", coverageDesc: "Emergency management of poisoning, drug overdoses, envenomations, and chemical exposures. 24/7 poison control.", tags: ["Poisoning", "Overdose", "Antidotes", "Venom", "Chemical Exposure"], response: "4 Min", available: "24/7", cases: "2300+", hotline: "+1 (800) POISON-NOW", image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=1200" }
];

// ✅ Sirf yeh line fix ki gayi hai - variable name `doctorsData` ki jagah `doctors` correct kiya
module.exports = { doctors, emergencyDoctors };
